name: End-to-end tests
on: 
  push:
    branches:
      - main
    paths:
      - '**.yml'
      - '**.json'
      - '**.js'
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Cache Cypress binary
        uses: actions/cache@v4
        id: cache-cypress
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: npm install

      - name: Update package-lock if needed
        run: |
          git diff --exit-code package-lock.json || (git add package-lock.json && git commit -m "Update package-lock.json [skip ci]" && git push)

      - name: Verify Cypress
        run: npx cypress verify

      - name: Cypress run
        run: npm run cypress:headless