name: End-to-end tests
on: 
  push:
    branches:
      - main
    paths:
      - '**.yml'
      - '**.json'
      - '**.js'
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
      # Carrega todas as variáveis necessárias
      SAUCEDEMO_USERNAME: ${{ secrets.SAUCEDEMO_USERNAME }}
      SAUCEDEMO_PASSWORD: ${{ secrets.SAUCEDEMO_PASSWORD }}
      SAUCEDEMO_INVALIDUSERNAME: ${{ secrets.SAUCEDEMO_INVALIDUSERNAME }}
      SAUCEDEMO_INVALIDPASSWORD: ${{ secrets.SAUCEDEMO_INVALIDPASSWORD }}
    permissions:
      contents: read 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify environment variables
        run: |
            echo "SAUCEDEMO_USERNAME: ${SAUCEDEMO_USERNAME:0:1}***${SAUCEDEMO_USERNAME: -1}"
            echo "SAUCEDEMO_PASSWORD: ${SAUCEDEMO_PASSWORD:0:1}***"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Cache Cypress binary
        uses: actions/cache@v4
        id: cypress-cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: |
          npm install
          # Força a instalação do Cypress se o cache não foi restaurado
          if [ "${{ steps.cypress-cache.outputs.cache-hit }}" != 'true' ]; then
            npx cypress install
          fi

      - name: Verify Cypress binary
        run: npx cypress verify

      - name: Run Cypress tests
        run: npm run cypress:headless